update yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -6,6 +6,7 @@ on:
     branches: [ main, master ]
 jobs:
   test:
+    name: Test
     timeout-minutes: 60
     runs-on: ubuntu-latest
     steps:
@@ -32,38 +33,60 @@ jobs:
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
-    - name: Checkout GitHub Pages branches
+    - name: Get Allure history
       uses: actions/checkout@v3
+      if: always()
+      continue-on-error: true
       with:
-        ref: main
-    - name: Set Git user
-      run: |
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-    - name: Download zipped HTML report
-      uses: actions/download-artifact@v3
+        ref: gh-pages
+        path: gh-pages
+    - name: Allure report action
+      uses: maryRom01/allure-report-action@main
+      if: always()
       with:
-        name: allure-results
-        path: allure-results
-    - name: Push HTML report
-      timeout-minutes: 3
-      run: |
-        git add .
-        git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
+        allure_results: allure-results
+        allure_history: allure-history
+        keep_reports: 10
+    - name: Deploy report to GitHub Pages
+      if: always()
+      uses: peaceiris/actions-gh-pages@v3
+      env:
+        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        PUBLISH_BRANCH: gh-pages
+        PUBLISH_DIR: allure-history    
 
-        while true; do 
-          git pull --rebase
-          if [ $? -ne 0 ]; then
-            echo "Failed to rebase. Please review manually."
-            exit 1
-          fi 
+    # - name: Checkout GitHub Pages branches
+    #   uses: actions/checkout@v3
+    #   with:
+    #     ref: main
+    # - name: Set Git user
+    #   run: |
+    #     git config --global user.name "github-actions[bot]"
+    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
+    # - name: Download zipped HTML report
+    #   uses: actions/download-artifact@v3
+    #   with:
+    #     name: allure-results
+    #     path: allure-results
+    # - name: Push HTML report
+    #   timeout-minutes: 3
+    #   run: |
+    #     git add .
+    #     git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
 
-          git push 
-          if [$? -eq 0 ]; then
-            echo "Successfully pushed HTML report to repo"
-            exit 0
-          fi  
-        done
+    #     while true; do 
+    #       git pull --rebase
+    #       if [ $? -ne 0 ]; then
+    #         echo "Failed to rebase. Please review manually."
+    #         exit 1
+    #       fi 
+
+    #       git push 
+    #       if [$? -eq 0 ]; then
+    #         echo "Successfully pushed HTML report to repo"
+    #         exit 0
+    #       fi  
+    #     done
    
 
 
