update yml file (report)

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -25,12 +25,41 @@ jobs:
         name: playwright-report
         path: playwright-report/
         retention-days: 30
-    - name: Publish HTML report 
-      if: always()
-      uses: peaceiris/actions-gh-pages@v3.7.3
+  publish_report:
+    name: Publish HTML report
+    if: always()
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    steps:
+    - name: Checkout GitHub Pages branches
+      uses: actions/checkout@v3
       with:
-        github_token: ${{secrets.GITHUB_TOKEN}}
-        publish_dir: playwright-report/
-        keep_files: true
-        user_name: 'github_actions[bot]'
-        user_email: 'github_actions[bot]@users.github.com'
+        ref: main
+    - name: Set Git user
+      run:
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+    - name: Download zipped HTML report
+      uses: actions/download-artifact@v3
+      with:
+        name: playwright-report
+        path: ${{ env.HTML_REPORT_URL_PATH }}
+    - name: Push HTML report
+      timeout-minutes: 3
+      run: |
+        git add .
+        git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
+        while true; do 
+          git pull --rebase
+          if [ $? -ne 0]; then
+            echo "Failed to rebase. Please review manually."
+            exit 1
+          fi  
+          if [$? -eq 0]; then
+            echo "Successfully pushed HTML report to repo"
+            exit 0
+          fi  
+        done
+   
+
+
